name: Check that commit is conventional

on: pull_request

permissions:
  contents: read

jobs:
  get-next-version:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: "false"
          show-progress: "false"

      - name: Check if commits are conventional
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          command: check
          args: --from-latest-tag --ignore-fixup-commits --ignore-merge-commits

      - name: Get next version
        id: next
        run: |
          NEXT_VERSION=$(cog bump --auto --dry-run |
            sed --silent --regexp-extended 's/^v([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)$/\1/p')
          echo "version=${NEXT_VERSION}" | tee --append "${GITHUB_OUTPUT}"
