name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: "false"
          show-progress: "false"

      - name: Get modified .go directories compared to ${{ github.event.repository.default_branch }} branch
        id: go
        run: |
          set -o pipefail
          FILE=$(mktemp --tmpdir="${RUNNER_TEMP}")
          gh pr view "${PR}" --json files --jq '.files[].path' |
            grep --invert-match --regexp='_test\.go$' |
            sed --regexp-extended --silent 's,^(.*)/[^/]+\.go$,./\1,p' |
            sort --unique | tee "${FILE}"
          set -o noglob
          set -- $(wc --lines "${FILE}")
          if [ "${1}" -gt 0 ]; then
            echo altered=true | tee --append "${GITHUB_OUTPUT}"
          else
            echo altered=false | tee --append "${GITHUB_OUTPUT}"
          fi
          rm --force -- "${FILE}"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ github.event.pull_request.number }}

      - name: golangci-lint
        if: steps.go.outputs.altered == 'true'
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version-file: .golangci-lint-version
