name: Run tests

on: pull_request

permissions:
  contents: read

jobs:
  go-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: "false"
          show-progress: "false"

      - name: Get modified .go directories compared to ${{ github.event.repository.default_branch }} branch
        id: go
        run: |
          set -o pipefail
          DIRS=$(gh pr view "${PR}" --json files --jq '.files[].path' |
            sed --regexp-extended --silent 's,^(.*)/[^/]+\.go$,./\1,p' |
            sort --unique | xargs)
          if [ -n "${DIRS}" ]; then
            TEST_FILES=$(find ${DIRS} -name '*_test.go' -type f | xargs)
            if [ -n "${TEST_FILES}" ]; then
              DIRS=$(dirname ${TEST_FILES} | sort --unique | xargs)
              echo "dirs=${DIRS}" | tee --append "${GITHUB_OUTPUT}"
              exit
            fi
          fi
          echo dirs= | tee --append "${GITHUB_OUTPUT}"
        env:
          GH_TOKEN: ${{ github.token }}
          PR: ${{ github.event.pull_request.number }}

      - name: Setup Go
        if: steps.go.outputs.dirs != ''
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          cache: false

      - name: Disable Go telemetry
        if: steps.go.outputs.dirs != ''
        run: go telemetry off

      - name: Run tests
        if: steps.go.outputs.dirs != ''
        run: |
          set -o pipefail
          FILE=$(mktemp --tmpdir="${RUNNER_TEMP}")
          trap "rm --force -- ${FILE}" INT HUP TERM EXIT
          MODULE_PATH=$(go mod edit -json | jq --raw-output .Module.Path)
          go work edit -json | jq --raw-output '.Use[].DiskPath | select(. != ".")' >"${FILE}"
          go list ./... | sed --regexp-extended "s,^${MODULE_PATH},.," >>"${FILE}"
          awk --field-separator=/ '{ print NF-1 "\t" $0 }' "${FILE}" |
            sort --reverse --numeric-sort | cut --fields=2 | while read -r pkgdir; do
              for dir in ${DIRS}; do
                dir="${dir}/"
                test "${dir#${pkgdir}/}" = "${dir}" || go test -C "${pkgdir}" ./...
              done
            done
        env:
          DIRS: ${{ steps.go.outputs.dirs }}
          FILE: ${{ steps.tmp.outputs.file }}
